#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function replace-home-file {
  if [ -e ~/$1 ]; then
    mv -f ~/$1 ~/$1.old
  fi
  ln -s $SCRIPT_DIR/$2 ~/$1
}

replace-home-file .bash_profile bash_profile
replace-home-file .profile profile
replace-home-file .git-completion.bash git-completion.bash
replace-home-file .git-prompt.sh git-prompt.sh

replace-home-file bin bin
#ln -s $SCRIPT_DIR/bin/replaceall ~/bin/replaceall
#git submodule update --init --quiet
